bitemyapp/bloodhound

- src/Database/Bloodhound/Types.hs
Only verified on ES 1.2.1, but the fix is similiar to caecf0fe36ee12c26067081356269f45c11fe2fc.
> Adjusts the format of the OR filter

- src/Database/Bloodhound/Types.hs
This is based off nex-gen and changes the type of Score, which can sometimes be null.
> make score nullable

- bloodhound.cabal
- src/Database/Bloodhound/Types.hs
- tests/tests.hs
Useful for combining search result sets or defaulting when a search
can't be performed
> Add Monoid instance for Search Hits

- src/Database/Bloodhound/Types.hs
- tests/tests.hs
This adds the [Query Filter](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-query-filter.html) filter. Tested ok on ElasticSearch 1.5.2, and it ought to work on all versions since 0.90.
> Add Query Filter

- src/Database/Bloodhound/Types.hs
Previously, when IndexTemplates were serialized they would look like this:
{"settings":{"settings":{...
due to an oversight on my part. This PR fixes that.
> Fixed IndexTemplate serialization bug

- src/Database/Bloodhound/Client.hs
- src/Database/Bloodhound/Types.hs
- tests/tests.hs
According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html), `IndexSettings` are serialized as `index.number_of_[shards|replicas]`, not merely `shards|replicas`.
> Fixed bug with IndexSettings serialization

- bloodhound.cabal
- src/Database/Bloodhound/Client.hs
- tests/tests.hs
@bitemyapp Sorry, I missed a small bug based on the different way the query parameter renderer worked
> url query encoding bug

- src/Database/Bloodhound/Types.hs
Turns out if you have to implement instances (orphan or otherwise) for BH, it is pretty useful to export the full BH constructor. I can't really see any harm in exporting it other than if we at some point made a breaking change to the underlying value and were going to make it API-compatible by converting in runBH, but people would be using runBH anyways and would only be using the constructor for instance declarations/derivations.
> export BH constructor

- bloodhound.cabal
- src/Database/Bloodhound/Types.hs
Control.Monad.Error is deprecated since mtl-2.2.1.
mtl-compat is a module that backports the Control.Monad.Except module
providing backwards compatibility for users of mtl <= 2.2.0.
> Replace Control.Monad.Error with CM.Except via mtl-compat

- src/Database/Bloodhound/Client.hs
"withManager" is deprecated since http-client-0.4.18.
> Use "newManager" instead of deprecated "withManager"

- bloodhound.cabal
Generally seems like good practice for the readme but there's a clear
benefit to adding changelog.md to extra-source-files: it gets parsed by
hackage and linked right from the haddocks!
> Add readme and changelog to extra source files

- tests/tests.hs
So here's the test. The type has a docstring on it. Anything else you had in mind or should this do it?
> Add test for error parsing

- bloodhound.cabal
- src/Database/Bloodhound/Client.hs
- src/Database/Bloodhound/Types.hs
- tests/tests.hs
This is in reference to #79 and is meant for review. Apologies for the size and duration of the PR but most of the work was due to me pulling the string on the fact that aliases can include filters, which can include queries, so I had to add FromJSON instances for all of that.
A couple discussion points:
1. `getIndexAliases` seems like its the first case where its purely a GET operation with a non-trivial response type. I went with a response type of `Either EsError IndexAliases` and exported the utility function `parseEsResponse` to capture the case that all JSON responses should either parse as the intended type or EsError. Do note that this function does throw in the (AFAIK impossible) case that the response doesn't parse as either. At least it documents what it throws...
2. There are …
> Index aliases

- src/Database/Bloodhound/Client.hs
- src/Database/Bloodhound/Types.hs
I chose to target this towards index aliases. It could also be in its own branch or target master, not sure what's best. This branch is based off of the work on index-aliases.
Changes in this commit:
- Put a note on scanSearch's runtime properties
- Resolve a "todo" making ScrollId a proper newtype.
- Add low level api calls for getInitialScroll and advanceScroll, with
which scanSearch is now implemented.
'scanSearch' provides a high level but pretty limited functionality. It
scans over the entire search range and appends hits into a list. There
are a few problems with this approach:
1. It uses lazy lists and O(n) appends on each page fetched. This
probably isn't a big deal for small results sets but for larger ones
this could get inefficient. Which brings me to
2. It collects all the …
> Low level scroll

- bloodhound.cabal
- src/Database/Bloodhound/Client.hs
- src/Database/Bloodhound/Types.hs
- src/Database/Bloodhound/Types/Internal.hs
- tests/tests.hs
This is pretty much exactly as we discussed but with one difference: rather than having the request hook be in MonadBH m, its in IO. While dogfooding my own solution, I tried making the hook `forall m. MonadBH m => Request -> m Request` and it gave me some really nasty type inference issues. I didn't fret too much about switching to IO because there are two use cases for these hooks that I'm aware of:
1. HTTP Basic auth for ElasticSearch Shield.
2. Amazon request signing.
Both can happen in IO, and HTTP Basic doesn't even need that. If a user has to do something fancier, they'll likely be operating in their own ReaderT-based monad and can just `ask` the state and run their hook in IO.
I've documented things but I don't really see any way to test this because the standard distribution of …
> Add Request hook

- src/Database/Bloodhound/Client.hs
Don't mind the branch name, I got lazy.
This is actually the cause of a bug in real code. If you happen to be
using parseEsResponse (which uses respIsTwoHunna) to parse the result of
certain operations such as creating an index, those operations return a
201 and unjustly are deemed to be a failure. I will not disclose how
long this took me to figure out the true cause ;)
> make respIsTwoHunna more semantic

- src/Database/Bloodhound/Types.hs
Addresses https://github.com/bitemyapp/bloodhound/issues/97 in the laziest way possible.
> no-op: improve EsProtocolException docs around PEBKAC errors

- src/Database/Bloodhound/Types.hs
- tests/tests.hs
Addresses https://github.com/bitemyapp/bloodhound/issues/99
I would write a test for this, but I've been unable to get the tests to run locally.
1) `cabal install -j --only-dependencies --enable-tests` outputs this error:
```
src/Test/Hspec/Core/Type.hs:152:20:
Constructor ‘HUnitFailure’ should have 2 arguments, but has been given 1
In the pattern: HUnitFailure err
In the first argument of ‘E.Handler’, namely
‘(\ (HUnitFailure err) -> return (Fail err))’
In the expression:
E.Handler (\ (HUnitFailure err) -> return (Fail err))
```
2) To fix the above error, I update the `hspec` bounds in `bloodhound.cabal` from `>= 1.8 && <2.2` to `>= 2.0 && <2.2`
3) Moving to hspec 2.0 causes this error:
```
tests/tests.hs:488:10:
Duplicate instance declarations:
instance (Arbitrary k, Ord k, Arbitrary v) …
```
> Add Missing Aggregation support

- bloodhound.cabal
- src/Database/Bloodhound/Types.hs
Addresses https://github.com/bitemyapp/bloodhound/issues/88
This is a backwards-incompatible change because the type of the `termKey` record in `TermsResult` and the signature of `BucketAggregation.key` have changed.
Some things I'm not sure about:
1) What is the `BucketAggregation` class used for? Is it okay to just convert `Scientific` and `Bool` keys to `Text`?
2) I'm a little concerned about the `Scientific` `Show` instance.  A JSON integer, `123` for example, will display as "123.0" as a `Scientific`. Is this acceptable?
Edit: reflect new content
> Support Bool and Numeric keys in TermsResults

- README.md
1) I noticed that the README says that TravisCI tests against `1.0.3, 1.1.2, 1.2.3, 1.3.2, and 1.4.0`, but if you look in TravisCI itself, the versions are `1.2.4, 1.3.6, 1.4.1, 1.5.2, 1.6.0, and 1.7.2`. Is the README out of date?
2) What are the `es14` etc functions for in [tests.hs] (https://github.com/bitemyapp/bloodhound/blob/master/tests/tests.hs#L69)?
> Add local testing instructions to README

- src/Database/Bloodhound/Types.hs
Now that I've picked up the latest content via our own vendor version...I realize that I forgot to export `BucketValue`! :cry:
> Doh, need to export BucketValue

- src/Database/Bloodhound/Types.hs
It's funny what you discover once you start eating your own dog food =)
Add the `MissingResult` data type (akin to `TermsResult`) and `toMissing` helper function for parsing `MissingResults` from `AggregationResults`.
> Add helper data types and functions for Missing Aggregations

- src/Database/Bloodhound/Client.hs
- tests/tests.hs
Probably the quickest feature add ever for bloodhound. This feature becomes useful if you do time-based indexes and need to retire old data.
> Add list indices feature

- src/Database/Bloodhound/Client.hs
The haddocks are currently reading the forward slashes to mean to italicize:
> Fix Haddocks italicizing forward slashes

- src/Database/Bloodhound/Client.hs
I can see why the smart constructor for shard count has a minimum of 0
but a replica count of 0 is totally valid.
> Support replica count of 0

- bloodhound.cabal
- stack-7.10.yaml
There were either some functions removed in the http-client 0.4 line or
ones added in 0.5 but after binary searching the version range, 0.4.30
seems to be the magic number where everything compiles and the tests
pass without having to do any CPP or worse.
> Set minimum lower bound on http-client

- src/Database/Bloodhound/Client.hs
Just a simple change. Client functions already roughly followed a grouping, but I added headings to the client so the haddocks are less daunting. It would probably be a good idea to do this some day to the types module but this is a good start.
> Break up client API into sections

- README.md
The first example doesn't work without the OverloadedStrings extension. The Server keeps demanding it's argument to be of the type Text
> Added the OverloadedStrings extension to first example in README.md

- src/Database/Bloodhound/Types.hs
- tests/tests.hs
So i'm going to break all the rules and have 2 different things in this pull request.
This pull request is the start of getting unit tests passing against the latest 2.3 elasticsearch, while not removing support for the current set.
First difference is that the status response no longer contains a status value.[1]  Which i'm just defaulting to 200.
Second is that the error format has changed.  I have attempted to maintain API compatibility and therefore not exposed the full information which is available in the response.  You can see a couple of examples of errors at [2] and [3].  I am using the 'reason' property as hopefully it is more user friendly in explaining the actual issue.   There does seem value in changing the API to support all of the information contained response.  What is …
> Beginnings of ES2 support - status page and error handling

- src/Database/Bloodhound/Types.hs
- tests/tests.hs
This pull request adds support for the Query side of cardinality aggregations.  The metric agg results are still unparsed
[ES Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-aggregations-metrics-cardinality-aggregation.html)
> Add support for cardinality aggregations

- tests/tests.hs
So it seems that to create parent child mappings in 2+ you must first create the child mapping AND then the parent.
Also 2+ has made indexes more strict.
If an index has multiple types which have matching properties then the types of those properties must be the same.
So in this example both the TweetMapping and ParentMapping must have the same types for the user, message, age, etc properties
maybe better explained by https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_conflicting_field_mappings
> Fix parent child tests for 2.0.

- src/Database/Bloodhound/Types.hs
So this lets an additional test pass on ES 2.0 due to stricter date parsing ( no more than that sadly )
It changes the date formatting to have leading 0's e.g.  02-02-2002.
It also removes more code than it adds :)
> Format date as dd-MM-yyyy to support stricter 2.0+

- bloodhound.cabal
- changelog.md
- src/Database/Bloodhound/Types.hs
The version number issue is OS-agnostic, the LoadAvgs issue is Windows-specific. 
The latter could have been dealt with using a CPP, but I generally try to avoid that. 
This is a breaking change, but it's recent stuff, so I didn't know what you wanted me to do with the version numbers. (Also, I had to make other changes there for windows, which I'm going to keep separate until my 2.4 work pushes forward).
> Wrap VersionNumber and LoadAvgs in Maybe #138

- .gitignore
- README.md
- src/Database/Bloodhound/Client.hs
- tests/tests.hs
No need to specify the mapping name twice, since `putMapping` does `PUT /$INDEXNAME/_mappings/$MAPPINGNAME` and you give it an `IndexName` and a `MappingName`. In fact, specifying the mapping name here breaks upsert semantics (you get `Root type mapping not empty after parsing!` exception when trying to add the same mapping twice).
> Fix an example.

- bloodhound.cabal
- src/Database/Bloodhound/Client.hs
- stack-7.10.yaml
- stack-7.8.yaml
- stack-8.0.yaml
AFAICT we weren't even using it anymore. We imported the function assert
and then never used it in the doctests.
This is for #146. We'll see what travis says.
> Drop doctest-prop

- tests/tests.hs
Due to the way node attr filters are serialized (attr name as an object
key), its possible to express a value in haskell that will parse
ambiguously. If we wanted to move the invariant into the types we could
use a map I guess but whatever.
I ran this updated test through 100,000 tests and we're all green.
This resolves #149
> Fix quickcheck failure due to ambiguous parse

- .travis.yml
- bloodhound.cabal
- stack-7.8.yaml
- tests/tests.hs
Until https://github.com/nick8325/quickcheck/pull/112 is merged and
released
AFAICS, this is the last bit, so we can put `bloodhound` back on Stackage again.
> Switch derive to generics-sop

- src/Database/V1/Bloodhound/Client.hs
- src/Database/V1/Bloodhound/Types.hs
- src/Database/V5/Bloodhound/Client.hs
- src/Database/V5/Bloodhound/Types.hs
- stack-7.8.yaml
- tests/V1/tests.hs
- tests/V5/tests.hs
This PR adds two functionalities:
* Inline 'template queries', which can be passed to the "_search" endpoint [1]
* A framework for 'suggesters' [2], with support for the 'Phrase Suggester' [3].
* It also includes a test which was requested in #172
A few notes:
* Tests for the new types and functions are included, along with some helper functions.
* Currently, this we're limiting to one suggestion request per search, although elastic supports 'n'.
[1] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-template-query.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters.htm
[3] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-phrase.html
> Support for 'Suggesters' and 'Template Queries'

- src/Database/V1/Bloodhound/Types.hs
- src/Database/V5/Bloodhound/Types.hs
Compiling with GHC 8.0.1 and warnings as errors I had the following issues:
```haskell
[ 3 of 10] Compiling Database.V5.Bloodhound.Types ( src/Database/V5/Bloodhound/Types.hs, dist/build/Database/V5/Bloodhound/Types.o )
src/Database/V5/Bloodhound/Types.hs:2101:10: warning: [-Wredundant-constraints]
• Redundant constraint: BucketAggregation a
• In the instance declaration for ‘FromJSON (Bucket a)’
src/Database/V5/Bloodhound/Types.hs:5242:1: warning: [-Wunused-top-binds]
Defined but not used: ‘mkPhraseSuggesterCollate’
```
This change is just fixing those issues for V5 and V1. I didn't really dig into the code too much so if I'm barking up the wrong tree please let me know.
> Fixup warnings about unused function and redundant constraints.

- bloodhound.cabal
It make more sense to have ES5 as default for tests rather than ES1.
> ES5 default for tests

- examples/Tweet.hs
Without this change, code compile but fail against ES, since names for lat lon (in Location record) don't follow specification for geo_point. I changed to use Types.LatLon instead.
There is still a problem with the example regarding the IndexTemplate. However that is not addressed in this PR.
> Use Types.LatLon for location

- bloodhound.cabal
- stack-8.2.yaml
I tested this locally, but I'm not really sure its the right thing to
put http-types in the default stack.yaml
This is for https://github.com/fpco/stackage/issues/3232 which blocks
us in katip-elasticsearch downstream
Update: @bitemyapp I noticed you actually put the http-types-0.11 in the stack.yaml in the last commit. Should I instead put 0.12 in the stack.yaml? Wasn't sure about the policy but I may have guessed wrong.
> Allow http-types-0.12

- src/Database/V5/Bloodhound/Types.hs
- tests/V5/tests.hs
Add support for token filters. The supported filters include: lowercase, uppercase, shingle, snowball, apostrophe, and reverse. This PR also adds tests for all of these.
> Add support for token filters

- bloodhound.cabal
`bloodhound` compiles against `http-client-0.6.1` and seems to work fine. The only breaking change in the new `http-client` was in the `renderParts` function, but it looks like `bloodhound` code doesn't make use of it.
Would be nice if you could make a Hackage revision too.
> Relax the dependency on http-client.

- src/Database/V5/Bloodhound/Client.hs
- src/Database/V5/Bloodhound/Internal/Aggregation.hs
- src/Database/V5/Bloodhound/Types.hs
- tests/V5/Test/Generators.hs
- tests/V5/Test/Sorting.hs
- tests/V5/tests.hs
This adds support for https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html
I decided to make the type `search_after` as `[Aeson.Value]` because this can be anything based on what user specified in `sort` body (in `Search`). `SearchAfterKey` is just type synonym to `[Aeson.Value]`.
Please let me know if this is okay. We are actually using this in production soon at [Plow](https://github.com/plow-technologies/) and it would be great if this PR can be merged so we can use the upstream version instead of our forked version.
> Add support for Search After API

- changelog.md
- src/Database/V5/Bloodhound/Internal/Newtypes.hs
- src/Database/V5/Bloodhound/Internal/Query.hs
- tests/V5/Test/Query.hs
This enables a "fuzziness" option for a Match Query: https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness
1. `MatchQuery` has a new field `matchQueryFuzziness` to add a "fuzziness" value
2. A `Fuzziness` value can be also created with an empty constructor FuzzinessAuto which sets fuzziness to a string value of "AUTO" 
I added a test for a fuzzy match query which works, but I am having trouble fixing some quick check JSON isomorphic tests. I have little experience with quick check and it ~~seems random properties fail~~ Never mind, it's all green here. 
Resolves #240
> Match query fuzziness

- changelog.md
- src/Database/Bloodhound/Client.hs
- src/Database/Bloodhound/Internal/Client.hs
- src/Database/Bloodhound/Types.hs
- tests/Test/BulkAPI.hs
Supercedes #250 
This adds an extra `Bulk` operation, with upsert semantics and the ability to pass some extra metadata that isn't possible with the existing API.
We've also added some tests for it, so hopefully it should be maintainable :)
> Add 'BulkUpsert' operation (now with tests)

- bloodhound.cabal
- cabal.project
- src/Database/V1/Bloodhound/Internal/Client.hs
- src/Database/V1/Bloodhound/Internal/Query.hs
- src/Database/V5/Bloodhound/Internal/Client.hs
- src/Database/V5/Bloodhound/Internal/Query.hs
- tests/V5/Test/Generators.hs
- tests/V5/Test/Import.hs
- tests/V5/Test/Snapshots.hs
While waiting for the next major release of Bloodhound, we'd like to use the current released version (0.16.0.0) with GHC 8.8 and 8.10 support. I'd appreciate if you can do a minor release 0.16.0.1 to make life easier for current users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bitemyapp/bloodhound/269)
> Support GHC 8.8 for 0.16.0.0

- src/Database/Bloodhound/Client.hs
It occurs that the endpoint called lacked the `"_doc"` part: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete.html
> Fix deleteDocument endpoint

- bloodhound.cabal
- src/Database/Bloodhound/Client.hs
- src/Database/Bloodhound/Internal/PointInTime.hs
- src/Database/Bloodhound/Types.hs
- tests/Test/Common.hs
- tests/Test/Sorting.hs
- tests/tests.hs
Adds support for https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html, which is now recommended over the scroll API for deep pagination.
I considered introducing a new exception type, or returning an error, instead of using `error` in `pitSearch` and `pitAccumulator`, but the cases they handle _should_ be impossible.
In the future it would be nice to introduce [advanceScroll](https://github.com/bitemyapp/bloodhound/blob/4775ebb759fe1b7cb5f880e4a41044b2363d98af/src/Database/Bloodhound/Client.hs#L1169) type functionality for the PIT API. This will require [passing some state around](https://github.com/mirokuratczyk/bloodhound/blob/36c682c63cb0268c3b9711403be7fbd608235666/src/Database/Bloodhound/Client.hs#L1241-L1243) between calls so I left it out for now, …
> Point in time (PIT) API support

- bloodhound.cabal
This change prevents compilation error when building with aeson-1:
src/Bloodhound/Import.hs:28:1: error:
Could not find module ‘Data.Aeson.Key’
> Update aeson min-bound to >=2.0

- README.md
> Remove old version compatibility note from the README

- flake.lock
- flake.nix
- shell.nix
It's usually better to have one source of truth (regarding package sources/versions) than two. So, use the compatibility mixin for those who want to keep using shell.nix.
GHC 9.2 is not supported anymore ("end of life".) Thus, we don't need overrides for it.
> chore: Let shell.nix depend on nix flake

- .github/workflows/compat.yml
- .github/workflows/haskell-ci.yml
This resolves deprecation warnings for v3.
> chore: Update actions/cache plugin (Github CI)

- src/Database/Bloodhound/Internal/Client/BHRequest.hs
- tests/Test/JSONSpec.hs
The error format changed.
The solution isn't ideal as it drops all but the first failure. However, it's better than having to deal with `EsProtocolException`s.
The this would fix https://github.com/bitemyapp/bloodhound/issues/295
> fix: Parsing EsError for OpenSearch 1.3

- .gitignore
- Makefile
- README.md
Looks like the stack project configuration has been removed before. This PR adjusts the `Makefile` accordingly (please see commit messages) and updates the docs.
> chore: Replace stack by cabal in Makefile

- flake.nix
`dockerd` relies on superuser/system access and thus should be provided by the operating system. However, `docker-compose` simply uses `dockerd` and thus can be part of the flake's dependencies for the `devShell`.
> feature: Add docker-compose to flake / devShell

- .github/workflows/compat.yml
The assumption is that most people will run the latest stable version of OpenSearch 1.3.x (if they chose 1.x instead of 2.x.) Thus, we should test compatibility with this version.
> chore: Test compatibility with OpenSearch 1.3.19
