README.md
bloodhound.cabal
src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Types.hs
tests/tests.hs

Turns out that there is a path for rendering queries in http-types. Also turns out that I hadn't run the Enum tests and they had some erros which I fixed. Working on getting Travis to build on our fork but I think it should build this when there's a PR. Please don't hesitate to let me know if there's anything you're iffy on. I don't want our immediate need to rush something unfinished out the door.

44 versioning

---

src/Database/Bloodhound/Client.hs

Fixed problem with put sending POST

---

bloodhound.cabal
src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Types.hs
tests/tests.hs

Added ability to manipulate templates

---

src/Database/Bloodhound/Client.hs

Fixed mapping API

---

src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Types.hs

https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html

Added ability to specify a parent document

---

README.md
src/Database/Bloodhound/Types.hs
tests/tests.hs

This will affect #57. Tests run on my machine but we shall see what travis says.

Eliminate partiality in EsResult

---

src/Database/Bloodhound/Types.hs
tests/tests.hs

This also adds a newtype for script. I would recommend the "Either Text
Text" for TermsAggregation be instead Either FieldName Script, but that
isn't directly related to this PR.

Add value_count aggregation support

---

src/Database/Bloodhound/Types.hs
tests/tests.hs

Note that this builds off of pull request #60 and should be merged afterwards. This adds the ability to do recursive filter aggregations.

Add filter aggregation support

---

src/Database/Bloodhound/Types.hs

Took a stab at #65 and it didn't require me to add any direct dependencies.

Take a stab at deriving Monad(Throw|Catch|Mask)

---

src/Database/Bloodhound/Client.hs
tests/tests.hs

This may not be the best way to approach the problem. See #62.

Added parent support to documentExists

---

src/Database/Bloodhound/Types.hs

Don't merge this yet. Its a discussion point
We still should discuss having a either a sum type or other affordance
for the case of parsing a response body which could be an error. You
can't just simply parse Either ESError a because aeson for some reason
provides an instance for (FromJSON a, FromJSON b) => FromJSON (Either a
b) which is highly Haskell-centric.
Bloodhound currently defines some convenient wrappers for happy path responses but nothing for error cases. As best I can tell, they have a single format for errors: a code (which seems to be redundant with the HTTP status code) and a big ugly error message. I don't think we should go down the path of trying to parse the message, but the type I provide here is enough to do some simple pattern matching on status which is about all …

Add a type for errors (for your consideration)

---

src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Types.hs
src/Database/Bloodhound/Types/Class.hs

Let me know what you think. For the most part this is a rote translation of ES' docs, I have no idea what a lot of these settings actually do. In some cases the docs gave no guidance as to what the JSON should actually look like so I've gathered the types from looking at stack overflow. I've improved type specificity where sensible (NominalDiffTime for time intervals, NonEmpty where applicable).
Let me know what you think and if you think anything else is needed. I didn't really have any ideas for exhaustive testing of that since it has to go to a live server to take effect.

Update index settings

---

README.md

This should resolve the mangling that happened when converting from org mode in #90

90 markdown bugs

---

README.md
src/Database/Bloodhound/Client.hs

Addresses https://github.com/bitemyapp/bloodhound/issues/95

Fix docs specifying an incorrect terminating condition

---

src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Types.hs
tests/tests.hs

Handy API to have it you ever want to get disk space back from ElasticSearch.

Implement index optimization

---

src/Database/Bloodhound/Types.hs

I wanted to read a `Filter` and it kinda escalated…

Add Read instances

---

src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Types.hs
tests/tests.hs

I just needed 1 field of this but the completionist (or masochist?) in me decided to implement the parsing of the whole stats API. As with the last type of API here, I pretty much can only use the tests as a smoke test since the stats are highly variable, but they are passing. I've merged in master so I should be up to date there.

Node stats api

---

changelog.md

Damn, there's a lot of PRs in this release. Should be ready to go.

Prepare for 0.12.0.0 release.

---

.travis.yml

For #166 
Just lowers the number of quicktests

lower quicktests to 500

---

src/Database/V1/Bloodhound/Types.hs
src/Database/V5/Bloodhound/Types.hs

Adds semigroup superclass to types implementing monoids. The failures in travis appear to be from master.

Semigroups

---

src/Database/V5/Bloodhound/Client.hs

Elasticsearch 2/5 seems to be able to do sorted scrolling searches. I wanted to make a sorted scroller, and this worked well for me.

Sorted version of getInitialScroll for V5 client

---

.travis.yml

Add travis output to prevent stalling

---

examples/README.md

Add a few run instructions to make it easier for newbies.

Run instructions in examples README

---

src/Database/V5/Bloodhound/Client.hs
tests/V5/tests.hs

resolves https://github.com/bitemyapp/bloodhound/issues/199

add function for deleting alias

---

src/Database/V5/Bloodhound/Client.hs
src/Database/V5/Bloodhound/Types.hs
tests/V5/tests.hs

resolves https://github.com/bitemyapp/bloodhound/issues/148

bulk create encoding

---

src/Database/V5/Bloodhound/Types.hs
tests/V5/tests.hs

resolves https://github.com/bitemyapp/bloodhound/issues/202

added maximum mapping size

---

src/Database/V5/Bloodhound/Client.hs

Needed for `defaultManagerSettings`

Add missing import

---

bloodhound.cabal
changelog.md

A couple of these changes broke API so I bumped the appropriate version. @bitemyapp  If everything looks good here I'll cut a release to hackage.

Prepare 0.15 release

---

src/Database/V5/Bloodhound/Types.hs
tests/V5/tests.hs

add ability to change compression codec. This allows us to use DEFLATE instead of lz4.

---

src/Database/V5/Bloodhound/Client.hs

Pretty simple addition. I'll wait to add tests until the test suite changes from https://github.com/bitemyapp/bloodhound/pull/223 are resolved.

add command for searching multiple indices

---

src/Database/Bloodhound/Client.hs
src/Database/Bloodhound/Internal/Count.hs
src/Database/Bloodhound/Types.hs
tests/Test/Count.hs
tests/tests.hs

Implement Count API

---

.github/workflows/haskell-ci.yml

- Test latest stable GHC 9.6.x version
- Test newer stable version: 9.8.2

chore: test more GHC versions

---

.github/workflows/compat.yml
docker-compose.yml

- Some tests fail with ElasticSearch 7.4.2
- Most people will likely use latest stable

Upgrate to es 7 latest stable
